### ISSUE TITLE
Numbers on voting results are really faint

### ISSUE THREAD

**Issue by vendion** [chadev/chadev-voting-booth#15]
Using Chrome 40 on Android Lollipop looking at the voting results the numbers are really faint and can be obscured by the faces.  See the sad and "meh" face in the attached screenshot.

![screenshot_2015-01-29-13-53-01](https://cloud.githubusercontent.com/assets/145018/5964063/2b759554-a7bf-11e4-94c2-39d4fc2e0c4e.png)

**Comment by jordanisip** [comment]
Thanks Adam, agreed.  The overlap on bar charts low percentage results look
wonky. Thanks for creating a ticket.

## 

Jordan Isip
Twitter: @fixie http://twitter.com/fixie

**Comment by jordanisip** [comment]
Put in a fix for this:

![screenshot](http://dl.dropbox.com/u/7502853/Screenshots/-so1fn5-lg68.png)
