### ISSUE TITLE
Setup Firebase Index

### ISSUE THREAD

**Issue by jordanisip** [chadev/chadev-voting-booth#18]
" FIREBASE WARNING: Using an unspecified index. Consider adding ".indexOn": "ended_at" at /votes to your security rules for better performance "

**Comment by keathley** [comment]
Changing the rules on firebase should fix this issue

```
{
  "rules": {
    ".read": true,
    ".write": true,
    "votes": {
      ".indexOn": ["ended_at"]
    }
  }
}
```

I did it in dev and it worked.

**Comment by jordanisip** [comment]
Nice that seemed to work, thanks @keathley!

Updated on https://chadev-voting-prod.firebaseio.com/?page=Security
